spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 3039988039@qq.com
    password: ozixvxiioyjjdegb
  rabbitmq:
    addresses: localhost
    virtual-host: /
  security:
    jwt:
      key: asdfghjkl
      expire: 12
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3309/bishe
